name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/che—Åkout@v2
    - name: Run a one-line script
      run: echo Hello,  world!

    - name: Run a multi-line script
      run: 
        echo Hello,  1 world!
        echo Hello,  2 world!
        echo Hello,  3 world!


